# Generated by Django 3.2.2 on 2021-05-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_guarantor', to='account.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanGuarantor',
        ),
    ]
