# Generated by Django 3.2.2 on 2021-05-25 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210524_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercard',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
