# Generated by Django 3.2.2 on 2021-05-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210525_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
