# Generated by Django 3.2 on 2021-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_guarantor_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
