# Generated by Django 3.2 on 2021-05-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usercard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='gateway',
            field=models.CharField(default='paystack', max_length=50, null=True),
        ),
    ]
