# Generated by Django 3.2 on 2021-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=50, null=True),
        ),
    ]
