# Generated by Django 3.2 on 2021-09-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_bvn'),
        ('account', '0010_alter_usercard_gateway'),
    ]

    operations = [
    ]
