# Generated by Django 3.2 on 2021-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20210929_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('super', 'Super')], default='user', max_length=20),
        ),
    ]
