# Generated by Django 3.2 on 2021-11-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
