# Generated by Django 3.2 on 2022-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220422_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
