# Generated by Django 3.2 on 2021-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saving',
            old_name='repayment_day',
            new_name='payment_day',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='balance',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='fixed_payment',
        ),
        migrations.AddField(
            model_name='saving',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='duration',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='last_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
