# Generated by Django 3.2 on 2021-08-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingtransaction',
            options={'ordering': ['-id']},
        ),
    ]
