# Generated by Django 3.2 on 2021-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20210427_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
