# Generated by Django 3.2 on 2021-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_saving_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='auto_save',
            field=models.BooleanField(default=True),
        ),
    ]
