# Generated by Django 3.2 on 2021-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20210916_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
