# Generated by Django 3.2 on 2021-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_saving_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingtransaction',
            old_name='payment_method',
            new_name='payment_gateway',
        ),
        migrations.AddField(
            model_name='saving',
            name='payment_gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=100),
        ),
    ]
