# Generated by Django 3.2 on 2021-10-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_alter_saving_payment_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingtransaction',
            options={},
        ),
    ]
