# Generated by Django 3.2 on 2021-05-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('basis', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50)),
                ('basis_duration', models.IntegerField(default=0)),
                ('number_of_days', models.IntegerField(default=1)),
                ('percentage', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('percentage_amount', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('amount_to_repay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_to_repay_split', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('last_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('next_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('unapproved', 'Unapproved'), ('awaiting_guarantor_feedback', "Awaiting guarantor's feedback"), ('ongoing', 'Ongoing'), ('repaid', 'Repaid')], default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('basis', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='month', max_length=50)),
                ('duration', models.IntegerField(default=1, help_text='This is the number of basis selected. If basis is monthly and basis number is 2, that means 2 months')),
                ('number_of_days', models.IntegerField(default=1)),
                ('percentage', models.DecimalField(decimal_places=2, default=20, max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('loan out', 'Loan out'), ('repayment', 'Loan repayment')], default='repayment', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('unsuccessful', 'Unsuccessful'), ('cancelled', 'Cancelled'), ('success', 'Success')], default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_days', models.IntegerField(default=180, help_text='This is the number of days user must have saved before eligible for loan')),
                ('maximum_loan', models.IntegerField(default=1, help_text='This is the maximum time a user can apply for loan when one is still active')),
                ('offer', models.DecimalField(decimal_places=2, default=3, help_text='This will be multiplied by user savings amount', max_digits=20)),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanduration'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
