# Generated by Django 3.2 on 2021-04-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0014_delete_saving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('number_of_days', models.IntegerField(default=1)),
                ('percentage', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('amount_to_repay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('last_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('next_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('unapproved', 'Unapproved'), ('awaiting guarantor feedback', "Awaiting guarantor's feedback"), ('ongoing', 'Ongoing'), ('repaid', 'Repaid')], default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50, unique=True)),
                ('number_of_days', models.IntegerField(default=1)),
                ('percentage', models.DecimalField(decimal_places=2, default=1, help_text='E.g: 1 means 1%, 10 means 10%', max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('loan out', 'Loan out'), ('repayment', 'Loan repayment')], default='repayment', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('unsuccessful', 'Unsuccessful'), ('cancelled', 'Cancelled'), ('success', 'Success')], default='pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profile')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanduration'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profile'),
        ),
    ]
