# Generated by Django 3.2 on 2021-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_days', models.IntegerField(default=180, help_text='This is the number of days user must have saved before eligible for loan')),
                ('maximum_loan', models.IntegerField(default=1, help_text='This is the maximum time a user can apply for loan when one is still active')),
            ],
        ),
    ]
