# Generated by Django 3.2 on 2021-05-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanSetup',
        ),
    ]
