# Generated by Django 3.2 on 2021-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_delete_loansetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=100),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
