# Generated by Django 3.2 on 2021-05-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('loan', '0002_loansetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansetup',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
