# Generated by Django 3.2 on 2021-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20210526_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_left_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
