# Generated by Django 3.2 on 2021-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loansetup_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansetup',
            name='offer_multiplication',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=20),
        ),
    ]
