# Generated by Django 3.2 on 2021-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_rename_offer_multiplication_loansetup_offer_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loansetup',
            name='offer_offer',
        ),
        migrations.AddField(
            model_name='loansetup',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=20),
        ),
    ]
