# Generated by Django 3.2 on 2021-09-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_rename_amount_left_to_pay_loan_amount_left_to_repay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantransaction',
            options={'ordering': ['-id']},
        ),
    ]
