# Generated by Django 3.2 on 2021-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20210504_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansetup',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=3, help_text='This will be multiplied by user savings amount', max_digits=20),
        ),
    ]
