# Generated by Django 3.2 on 2021-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loansetup_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanduration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
    ]
