# Generated by Django 3.2 on 2022-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_loan_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='basis',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annual', 'Bi-Annual')], default='monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanduration',
            name='basis',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annual', 'Bi-Annual')], default='month', max_length=50),
        ),
    ]
