# Generated by Django 3.2 on 2021-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_loanduration_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanduration',
            name='basis',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='month', max_length=50),
        ),
        migrations.AddField(
            model_name='loanduration',
            name='basis_number',
            field=models.IntegerField(default=1, help_text='This is the number of basis selected. If basis is monthly and basis number is 2, that means 2 months'),
        ),
    ]
