# Generated by Django 3.2 on 2021-05-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20210505_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanduration',
            name='basis_number',
        ),
        migrations.AddField(
            model_name='loanduration',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanduration',
            name='basis',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='month', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanduration',
            name='duration',
            field=models.IntegerField(default=1, help_text='This is the number of basis selected. If basis is monthly and basis number is 2, that means 2 months'),
        ),
    ]
