# Generated by Django 3.2 on 2021-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_auto_20210505_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanduration',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
