# Generated by Django 3.2 on 2021-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_alter_loanduration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='basis',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='basis_duration',
            field=models.IntegerField(default=0),
        ),
    ]
