# Generated by Django 3.2 on 2021-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_loan_percentage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_to_repay_split',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
