# Generated by Django 3.2 on 2021-04-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingtransaction',
            name='saving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.saving'),
        ),
    ]
