# Generated by Django 3.2.2 on 2021-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('membership fee', 'Membership Fee')], default='membership fee', max_length=100),
        ),
    ]
