# Generated by Django 3.2 on 2021-04-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_savingtransaction_saving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingTransaction',
        ),
    ]
