# Generated by Django 3.2 on 2021-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanSettings',
            new_name='LoanSetting',
        ),
    ]
