# Generated by Django 3.2 on 2021-05-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_loansettings_loansetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.settings'),
        ),
    ]
