# Generated by Django 3.2 on 2021-05-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_settings_generalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name_plural': 'General Settings'},
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
