# Generated by Django 3.2.2 on 2021-05-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20210524_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansetting',
            name='number_of_guarantor',
            field=models.PositiveIntegerField(default=0, help_text='This is the number of guarantor(s) a user must have to be eligible for a loan'),
        ),
    ]
