# Generated by Django 3.2 on 2021-09-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_generalsettings_membership_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loansetting',
            name='site',
        ),
    ]
