# Generated by Django 3.2 on 2022-06-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_investmentoption_duration'),
        ('superadmin', '0003_auto_20220425_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed'), ('declined', 'Declined'), ('approved', 'Approved')], default='pending', max_length=100)),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.userinvestment')),
            ],
        ),
    ]
