# Generated by Django 3.2 on 2022-06-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_investmentoption_duration'),
        ('superadmin', '0004_investmentwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentwithdrawal',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.userinvestment'),
        ),
    ]
