# Generated by Django 3.2 on 2021-04-26 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_duration_faq_faqcategory_feedbackmessage_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='date',
        ),
        migrations.AddField(
            model_name='saving',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.profile'),
        ),
    ]
