# Generated by Django 3.2 on 2021-04-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_saving_repayment_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='amount',
        ),
    ]
