# Generated by Django 3.2 on 2021-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_saving_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='last_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
