# Generated by Django 3.2 on 2021-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20210426_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='fixed_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
