# Generated by Django 3.2 on 2021-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_saving_fixed_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
