# Generated by Django 3.2 on 2021-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_saving_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='paid_membership_fee',
            field=models.BooleanField(default=False),
        ),
    ]
