# Generated by Django 3.2 on 2021-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_saving_paid_membership_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='paid_membership_fee',
        ),
        migrations.AddField(
            model_name='profile',
            name='paid_membership_fee',
            field=models.BooleanField(default=False),
        ),
    ]
