# Generated by Django 3.2 on 2021-04-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210427_1029'),
        ('transaction', '0002_alter_savingtransaction_saving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
