# Generated by Django 3.2 on 2021-07-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_usercard_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('basis', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='month', max_length=50)),
                ('duration', models.IntegerField(default=1, help_text='This is the number of basis selected. If basis is monthly and basis number is 2, that means 2 months')),
                ('number_of_days', models.IntegerField(default=30)),
                ('percentage', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.availableinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('key metric', 'Key metric'), ('minimum return', 'Minimum return'), ('target for return per annum', 'Target for return per annum'), ('investible asset claim', 'Investible asset claim'), ('30 days average return', '30 days average return'), ('return on investment', 'Return on investment')], max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('investment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investmentoption')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('return_on_invested', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('number_of_month', models.IntegerField(default=1)),
                ('number_of_days', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_duration', to='investment.investmentduration')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='investment.availableinvestment')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='investment.investmentoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='investmentspecification',
            constraint=models.UniqueConstraint(fields=('investment_option', 'key', 'value'), name='investment_spec_constraint'),
        ),
        migrations.AddConstraint(
            model_name='investmentoption',
            constraint=models.UniqueConstraint(fields=('investment', 'name'), name='investment_option_constraint'),
        ),
    ]
