# Generated by Django 3.2 on 2021-07-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investmentspecification',
            name='investment_spec_constraint',
        ),
        migrations.AddConstraint(
            model_name='investmentspecification',
            constraint=models.UniqueConstraint(fields=('investment_option', 'key'), name='investment_spec_constraint'),
        ),
    ]
