# Generated by Django 3.2 on 2021-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20210722_0915'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investmentoption',
            name='investment_option_constraint',
        ),
        migrations.RenameField(
            model_name='investmentoption',
            old_name='investment',
            new_name='available_investment',
        ),
        migrations.AddConstraint(
            model_name='investmentoption',
            constraint=models.UniqueConstraint(fields=('available_investment', 'name'), name='investment_option_constraint'),
        ),
    ]
