# Generated by Django 3.2 on 2021-07-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20210722_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoption',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.investmentduration'),
        ),
    ]
