# Generated by Django 3.2 on 2021-07-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_investmentoption_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentoption',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.investmentduration'),
        ),
    ]
