# Generated by Django 3.2 on 2021-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_alter_investmentoption_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
