# Generated by Django 3.2 on 2021-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_auto_20210723_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentoption',
            name='duration',
        ),
        migrations.AddField(
            model_name='investmentoption',
            name='duration',
            field=models.ManyToManyField(blank=True, null=True, to='investment.InvestmentDuration'),
        ),
    ]
