# Generated by Django 3.2 on 2021-10-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20210929_1150'),
        ('investment', '0010_alter_investmentoption_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Investment',
            new_name='UserInvestment',
        ),
        migrations.RemoveField(
            model_name='availableinvestment',
            name='status',
        ),
        migrations.AddField(
            model_name='availableinvestment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availableinvestment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investmenttype'),
        ),
    ]
