# Generated by Django 3.2 on 2021-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_auto_20211021_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableInvestment',
            new_name='Investment',
        ),
        migrations.RemoveConstraint(
            model_name='investmentoption',
            name='investment_option_constraint',
        ),
        migrations.RenameField(
            model_name='investmentoption',
            old_name='available_investment',
            new_name='investment',
        ),
        migrations.RenameField(
            model_name='investmenttransaction',
            old_name='investment',
            new_name='user_investment',
        ),
        migrations.AddConstraint(
            model_name='investmentoption',
            constraint=models.UniqueConstraint(fields=('investment', 'name'), name='investment_option_constraint'),
        ),
    ]
