# Generated by Django 3.2 on 2021-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_alter_investmenttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
