# Generated by Django 3.2 on 2021-10-22 09:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_auto_20211022_1021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='investmentoption',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='investmentoption',
            name='status',
        ),
    ]
