# Generated by Django 3.2 on 2021-10-22 09:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_auto_20211022_1044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='investmentoption',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='investmentoption',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
