# Generated by Django 3.2 on 2021-10-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0017_auto_20211026_2115'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investmentspecification',
            name='investment_spec_constraint',
        ),
        migrations.AddConstraint(
            model_name='investmentspecification',
            constraint=models.UniqueConstraint(fields=('option', 'key'), name='investment_spec_constraint'),
        ),
    ]
