# Generated by Django 3.2 on 2022-04-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_auto_20211026_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentoption',
            name='duration',
        ),
    ]
