# Generated by Django 3.2 on 2022-04-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0019_remove_investmentoption_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoption',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investmentduration'),
        ),
    ]
