# Generated by Django 3.2 on 2022-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_investmentoption_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='amount_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
